### ISSUE TITLE
Publish tagging for Scala.js 1.x

### ISSUE THREAD

**Issue by sbrunk** [softwaremill/scala-common#18]
I'm working on [porting Tapir over to Scala.js](https://github.com/softwaremill/tapir/pull/860) and it uses `tagging` (2.2.1) for some of the tests. Right now `tagging` is only published for Scala.js 0.6.x though.

It seems like the Scala.js plugin on master has already been updated to Scala.js 1.1:
https://github.com/softwaremill/scala-common/blob/e0ca082cc061345e49498b7a010d34b2a9b8aeec/project/plugins.sbt#L7

I could also build it locally. It would be awesome if you could publish a Scala.js 1.x artifact.

**Comment by adamw** [comment]
Should be in central soon (~15 minutes?)
