### ISSUE TITLE
tagging value classes does not work

### ISSUE THREAD

**Issue by kwark** [softwaremill/scala-common#8]
Hello,

This tagging library is suffering from the same issue as shapeless: https://github.com/milessabin/shapeless/issues/644

```
object Main extends App {

  trait FooTag
  case class A(value: Int) extends AnyVal

  import com.softwaremill.tagging._

  val foo = A(0).taggedWith[FooTag]

  println(Array(foo).apply(0))
  println(List(foo).head)

}
```

This will throw a `ClassCastException` 

You can also run/checkout this scastie: https://scastie.scala-lang.org/kwark/h4No8bhdQGKIEBV14rTkrA

A solution is to make `Tag` a universal trait instead of a type alias:

`trait Tag[+U] extends Any { type Tag <: U }`

Also see: https://scastie.scala-lang.org/kwark/575syCWTQIWsVaeJAKVxoQ

You might want to check binary compatibility.

**Comment by kciesielski** [comment]
Sorry for long silence, thanks a lot for reporting the issue and proposing a solution. As far as I checked it works well and there are no issues with binary compatibility. I'm preparing a proper fix.
